# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hardback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('hardback', 'title', 'author')]),
        ),
    ]
