# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 18:17
from __future__ import unicode_literals

from django.db import migrations, IntegrityError

from ..models import HORROR


def forwards(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Author = apps.get_model('books', 'Author')
    king, _ = Author.objects.get_or_create(name='Stephen King')
    try:
        Book.objects.create(
            title='It',
            isbn='124313135214342',
            genre=HORROR,
            fiction=True,
            author=king,
            hardback=True,
            price='9.99',
            in_stock=False
        )
    except IntegrityError:
        pass


def backwards(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    Author = apps.get_model('books', 'Author')
    try:
        king = Author.objects.get(name='Stephen King')
    except Author.DoesNotExist:
        pass
    else:
        try:
            it = Book.objects.get(title='It', hardback=True, author=king)
        except Book.ObjectDoesNotExist:
            pass
        else:
            it.delete()
            king.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_in_stock'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards)
    ]
